local parentAddonName = "EnhanceQoL"
local addonName, addon = ...
if _G[parentAddonName] then
	addon = _G[parentAddonName]
else
	error(parentAddonName .. " is not loaded")
end

addon.SharedMedia = addon.SharedMedia or {}

local effectPath = "Interface\\AddOns\\" .. addonName .. "\\Sounds\\Effects\\"
local voiceoverPath = "Interface\\AddOns\\" .. addonName .. "\\Sounds\\Voiceovers\\"

addon.SharedMedia.sounds = {
	-- Soundeffects
	{ key = "bloodlust", label = "For the Horde", path = effectPath .. "bloodlust.ogg" },
	{ key = "cartoonbite", label = "EQOL: Bite", path = effectPath .. "cartoonbite.ogg" },
	{ key = "gamingpunch", label = "EQOL: Punch", path = effectPath .. "gamingpunch.ogg" },
	{ key = "yougotmail", label = "EQOL: You Got Mail", path = effectPath .. "yougotmail.ogg" },

	-- Voiceovers
	{ key = "1", label = "EQOL: 1", path = voiceoverPath .. "1.ogg" },
	{ key = "2", label = "EQOL: 2", path = voiceoverPath .. "2.ogg" },
	{ key = "3", label = "EQOL: 3", path = voiceoverPath .. "3.ogg" },
	{ key = "4", label = "EQOL: 4", path = voiceoverPath .. "4.ogg" },
	{ key = "5", label = "EQOL: 5", path = voiceoverPath .. "5.ogg" },
	{ key = "6", label = "EQOL: 6", path = voiceoverPath .. "6.ogg" },
	{ key = "7", label = "EQOL: 7", path = voiceoverPath .. "7.ogg" },
	{ key = "8", label = "EQOL: 8", path = voiceoverPath .. "8.ogg" },
	{ key = "9", label = "EQOL: 9", path = voiceoverPath .. "9.ogg" },
	{ key = "10", label = "EQOL: 10", path = voiceoverPath .. "10.ogg" },
	{ key = "First", label = "EQOL: First", path = voiceoverPath .. "First.ogg" },
	{ key = "Second", label = "EQOL: Second", path = voiceoverPath .. "Second.ogg" },
	{ key = "Third", label = "EQOL: Third", path = voiceoverPath .. "Third.ogg" },
	{ key = "Fourth", label = "EQOL: Fourth", path = voiceoverPath .. "Fourth.ogg" },
	{ key = "Fifth", label = "EQOL: Fifth", path = voiceoverPath .. "Fifth.ogg" },
	{ key = "Star", label = "EQOL: |TInterface\\TargetingFrame\\UI-RaidTargetingIcon_1:16|tStar", path = voiceoverPath .. "Star.ogg" },
	{ key = "Circle", label = "EQOL: |TInterface\\TargetingFrame\\UI-RaidTargetingIcon_2:16|tCircle", path = voiceoverPath .. "Circle.ogg" },
	{ key = "Diamond", label = "EQOL: |TInterface\\TargetingFrame\\UI-RaidTargetingIcon_3:16|tDiamond", path = voiceoverPath .. "Diamond.ogg" },
	{ key = "Triangle", label = "EQOL: |TInterface\\TargetingFrame\\UI-RaidTargetingIcon_4:16|tTriangle", path = voiceoverPath .. "Triangle.ogg" },
	{ key = "Moon", label = "EQOL: |TInterface\\TargetingFrame\\UI-RaidTargetingIcon_5:16|tMoon", path = voiceoverPath .. "Moon.ogg" },
	{ key = "Square", label = "EQOL: |TInterface\\TargetingFrame\\UI-RaidTargetingIcon_6:16|tSquare", path = voiceoverPath .. "Square.ogg" },
	{ key = "Cross", label = "EQOL: |TInterface\\TargetingFrame\\UI-RaidTargetingIcon_7:16|tCross", path = voiceoverPath .. "Cross.ogg" },
	{ key = "Skull", label = "EQOL: |TInterface\\TargetingFrame\\UI-RaidTargetingIcon_8:16|tSkull", path = voiceoverPath .. "Skull.ogg" },
	{ key = "Adds", label = "EQOL: Adds", path = voiceoverPath .. "Adds.ogg" },
	{ key = "Add", label = "EQOL: Add", path = voiceoverPath .. "Add.ogg" },
	{ key = "Affix", label = "EQOL: Affix", path = voiceoverPath .. "Affix.ogg" },
	{ key = "AoE", label = "EQOL: AoE", path = voiceoverPath .. "AoE.ogg" },
	{ key = "Assist", label = "EQOL: Assist", path = voiceoverPath .. "Assist.ogg" },
	{ key = "Avoid", label = "EQOL: Avoid", path = voiceoverPath .. "Avoid.ogg" },
	{ key = "Back", label = "EQOL: Back", path = voiceoverPath .. "Back.ogg" },
	{ key = "Backup", label = "EQOL: Backup", path = voiceoverPath .. "Backup.ogg" },
	{ key = "Bait", label = "EQOL: Bait", path = voiceoverPath .. "Bait.ogg" },
	{ key = "Beam", label = "EQOL: Beam", path = voiceoverPath .. "Beam.ogg" },
	{ key = "Bleed", label = "EQOL: Bleed", path = voiceoverPath .. "Bleed.ogg" },
	{ key = "Blue", label = "EQOL: Blue", path = voiceoverPath .. "Blue.ogg" },
	{ key = "Bombs", label = "EQOL: Bombs", path = voiceoverPath .. "Bombs.ogg" },
	{ key = "Boss", label = "EQOL: Boss", path = voiceoverPath .. "Boss.ogg" },
	{ key = "Break", label = "EQOL: Break", path = voiceoverPath .. "Break.ogg" },
	{ key = "Buff", label = "EQOL: Buff", path = voiceoverPath .. "Buff.ogg" },
	{ key = "CC", label = "EQOL: CC", path = voiceoverPath .. "CC.ogg" },
	{ key = "Chain", label = "EQOL: Chain", path = voiceoverPath .. "Chain.ogg" },
	{ key = "Charge", label = "EQOL: Charge", path = voiceoverPath .. "Charge.ogg" },
	{ key = "Check", label = "EQOL: Check", path = voiceoverPath .. "Check.ogg" },
	{ key = "Clear", label = "EQOL: Clear", path = voiceoverPath .. "Clear.ogg" },
	{ key = "Collect", label = "EQOL: Collect", path = voiceoverPath .. "Collect.ogg" },
	{ key = "Dance", label = "EQOL: Dance", path = voiceoverPath .. "Dance.ogg" },
	{ key = "Debuff", label = "EQOL: Debuff", path = voiceoverPath .. "Debuff.ogg" },
	{ key = "Decurse", label = "EQOL: Decurse", path = voiceoverPath .. "Decurse.ogg" },
	{ key = "Defensive", label = "EQOL: Defensive", path = voiceoverPath .. "Defensive.ogg" },
	{ key = "Dodge", label = "EQOL: Dodge", path = voiceoverPath .. "Dodge.ogg" },
	{ key = "Dot", label = "EQOL: Dot", path = voiceoverPath .. "Dot.ogg" },
	{ key = "Don't", label = "EQOL: Don't", path = voiceoverPath .. "Don't.ogg" },
	{ key = "Don't move", label = "EQOL: Don't move", path = voiceoverPath .. "Don't move.ogg" },
	{ key = "Drop", label = "EQOL: Drop", path = voiceoverPath .. "Drop.ogg" },
	{ key = "Enrage", label = "EQOL: Enrage", path = voiceoverPath .. "Enrage.ogg" },
	{ key = "Enter", label = "EQOL: Enter", path = voiceoverPath .. "Enter.ogg" },
	{ key = "Exit", label = "EQOL: Exit", path = voiceoverPath .. "Exit.ogg" },
	{ key = "External", label = "EQOL: External", path = voiceoverPath .. "External.ogg" },
	{ key = "Fear", label = "EQOL: Fear", path = voiceoverPath .. "Fear.ogg" },
	{ key = "Feet", label = "EQOL: Feet", path = voiceoverPath .. "Feet.ogg" },
	{ key = "Fixate", label = "EQOL: Fixate", path = voiceoverPath .. "Fixate.ogg" },
	{ key = "Focus", label = "EQOL: Focus", path = voiceoverPath .. "Focus.ogg" },
	{ key = "Frontal", label = "EQOL: Frontal", path = voiceoverPath .. "Frontal.ogg" },
	{ key = "Gate", label = "EQOL: Gate", path = voiceoverPath .. "Gate.ogg" },
	{ key = "Gather", label = "EQOL: Gather", path = voiceoverPath .. "Gather.ogg" },
	{ key = "Green", label = "EQOL: Green", path = voiceoverPath .. "Green.ogg" },
	{ key = "Go", label = "EQOL: Go", path = voiceoverPath .. "Go.ogg" },
	{ key = "Grip", label = "EQOL: Grip", path = voiceoverPath .. "Grip.ogg" },
	{ key = "Hide", label = "EQOL: Hide", path = voiceoverPath .. "Hide.ogg" },
	{ key = "Immunity", label = "EQOL: Immunity", path = voiceoverPath .. "Immunity.ogg" },
	{ key = "In", label = "EQOL: In", path = voiceoverPath .. "In.ogg" },
	{ key = "Intermission", label = "EQOL: Intermission", path = voiceoverPath .. "Intermission.ogg" },
	{ key = "Interrupt", label = "EQOL: Interrupt", path = voiceoverPath .. "Interrupt.ogg" },
	{ key = "Invis", label = "EQOL: Invis", path = voiceoverPath .. "Invis.ogg" },
	{ key = "Invisibility", label = "EQOL: Invisibility", path = voiceoverPath .. "Invisibility.ogg" },
	{ key = "Jump", label = "EQOL: Jump", path = voiceoverPath .. "Jump.ogg" },
	{ key = "Kick", label = "EQOL: Kick", path = voiceoverPath .. "Kick.ogg" },
	{ key = "Kite", label = "EQOL: Kite", path = voiceoverPath .. "Kite.ogg" },
	{ key = "Knock", label = "EQOL: Knock", path = voiceoverPath .. "Knock.ogg" },
	{ key = "Last", label = "EQOL: Last", path = voiceoverPath .. "Last.ogg" },
	{ key = "Leap", label = "EQOL: Leap", path = voiceoverPath .. "Leap.ogg" },
	{ key = "Left", label = "EQOL: Left", path = voiceoverPath .. "Left.ogg" },
	{ key = "Line", label = "EQOL: Line", path = voiceoverPath .. "Line.ogg" },
	{ key = "Line of Sight", label = "EQOL: Line of Sight", path = voiceoverPath .. "Line of Sight.ogg" },
	{ key = "Link", label = "EQOL: Link", path = voiceoverPath .. "Link.ogg" },
	{ key = "Linked", label = "EQOL: Linked", path = voiceoverPath .. "Linked.ogg" },
	{ key = "LoS", label = "EQOL: LoS", path = voiceoverPath .. "LoS.ogg" },
	{ key = "Move", label = "EQOL: Move", path = voiceoverPath .. "Move.ogg" },
	{ key = "Next", label = "EQOL: Next", path = voiceoverPath .. "Next.ogg" },
	{ key = "Nuke", label = "EQOL: Nuke", path = voiceoverPath .. "Nuke.ogg" },
	{ key = "Orange", label = "EQOL: Orange", path = voiceoverPath .. "Orange.ogg" },
	{ key = "Out", label = "EQOL: Out", path = voiceoverPath .. "Out.ogg" },
	{ key = "Overlap", label = "EQOL: Overlap", path = voiceoverPath .. "Overlap.ogg" },
	{ key = "Poison", label = "EQOL: Poison", path = voiceoverPath .. "Poison.ogg" },
	{ key = "Pot", label = "EQOL: Pot", path = voiceoverPath .. "Pot.ogg" },
	{ key = "Pull", label = "EQOL: Pull", path = voiceoverPath .. "Pull.ogg" },
	{ key = "Purple", label = "EQOL: Purple", path = voiceoverPath .. "Purple.ogg" },
	{ key = "Push", label = "EQOL: Push", path = voiceoverPath .. "Push.ogg" },
	{ key = "Ready Check", label = "EQOL: Ready Check", path = voiceoverPath .. "Ready Check.ogg" },
	{ key = "Red", label = "EQOL: Red", path = voiceoverPath .. "Red.ogg" },
	{ key = "Reflect", label = "EQOL: Reflect", path = voiceoverPath .. "Reflect.ogg" },
	{ key = "Refresh", label = "EQOL: Refresh", path = voiceoverPath .. "Refresh.ogg" },
	{ key = "Right", label = "EQOL: Right", path = voiceoverPath .. "Right.ogg" },
	{ key = "Root", label = "EQOL: Root", path = voiceoverPath .. "Root.ogg" },
	{ key = "Shield", label = "EQOL: Shield", path = voiceoverPath .. "Shield.ogg" },
	{ key = "Soak", label = "EQOL: Soak", path = voiceoverPath .. "Soak.ogg" },
	{ key = "Soon", label = "EQOL: Soon", path = voiceoverPath .. "Soon.ogg" },
	{ key = "Spawn", label = "EQOL: Spawn", path = voiceoverPath .. "Spawn.ogg" },
	{ key = "Split", label = "EQOL: Split", path = voiceoverPath .. "Split.ogg" },
	{ key = "Spread", label = "EQOL: Spread", path = voiceoverPath .. "Spread.ogg" },
	{ key = "Stack", label = "EQOL: Stack", path = voiceoverPath .. "Stack.ogg" },
	{ key = "Stay", label = "EQOL: Stay", path = voiceoverPath .. "Stay.ogg" },
	{ key = "Stop", label = "EQOL: Stop", path = voiceoverPath .. "Stop.ogg" },
	{ key = "Stopcast", label = "EQOL: Stopcast", path = voiceoverPath .. "Stopcast.ogg" },
	{ key = "Swap", label = "EQOL: Swap", path = voiceoverPath .. "Swap.ogg" },
	{ key = "Switch", label = "EQOL: Switch", path = voiceoverPath .. "Switch.ogg" },
	{ key = "Stun", label = "EQOL: Stun", path = voiceoverPath .. "Stun.ogg" },
	{ key = "Targeted", label = "EQOL: Targeted", path = voiceoverPath .. "Targeted.ogg" },
	{ key = "Taunt", label = "EQOL: Taunt", path = voiceoverPath .. "Taunt.ogg" },
	{ key = "Transission", label = "EQOL: Transission", path = voiceoverPath .. "Transission.ogg" },
	{ key = "Turn", label = "EQOL: Turn", path = voiceoverPath .. "Turn.ogg" },
	{ key = "Use", label = "EQOL: Use", path = voiceoverPath .. "Use.ogg" },
	{ key = "Volley", label = "EQOL: Volley", path = voiceoverPath .. "Volley.ogg" },
	{ key = "Wave", label = "EQOL: Wave", path = voiceoverPath .. "Wave.ogg" },
	{ key = "Winds", label = "EQOL: Winds", path = voiceoverPath .. "Winds.ogg" },
	{ key = "Yellow", label = "EQOL: Yellow", path = voiceoverPath .. "Yellow.ogg" },
	{ key = "AMZ", label = "EQOL: |cFF000000|rAMZ |T237510:16|t", path = voiceoverPath .. "AMZ.ogg" },
	{ key = "Darkness", label = "EQOL: |cFF000000|rDarkness |T1305154:16|t", path = voiceoverPath .. "Darkness.ogg" },
	{ key = "Barkskin", label = "EQOL: |cFF000000|rBarkskin |T572025:16|t", path = voiceoverPath .. "Barkskin.ogg" },
	{ key = "Ironbark", label = "EQOL: |cFF000000|rIronbark |T572025:16|t", path = voiceoverPath .. "Ironbark.ogg" },
	{ key = "Incarnation", label = "EQOL: |cFF000000|rIncarnation |T571586:16|t", path = voiceoverPath .. "Incarnation.ogg" },
	{ key = "Innervate", label = "EQOL: |cFF000000|rInnervate |T136048:16|t", path = voiceoverPath .. "Innervate.ogg" },
	{ key = "Rage of the Sleeper", label = "EQOL: |cFF000000|rRage of the Sleeper |T1129695:16|t", path = voiceoverPath .. "Rage of the Sleeper.ogg" },
	{ key = "Roar", label = "EQOL: |cFF000000|rRoar |T463283:16|t", path = voiceoverPath .. "Roar.ogg" },
	{ key = "Tranquility", label = "EQOL: |cFF000000|rTranquility |T136107:16|t", path = voiceoverPath .. "Tranquility.ogg" },
	{ key = "Rescue", label = "EQOL: |cFF000000|rRescue |T4622460:16|t", path = voiceoverPath .. "Rescue.ogg" },
	{ key = "Rewind", label = "EQOL: |cFF000000|rRewind |T4622474:16|t", path = voiceoverPath .. "Rewind.ogg" },
	{ key = "Spatial Paradox", label = "EQOL: |cFF000000|rSpatial Paradox |T5199645:16|t", path = voiceoverPath .. "Spatial Paradox.ogg" },
	{ key = "Time Dilation", label = "EQOL: |cFF000000|rTime Dilation |T4622478:16|t", path = voiceoverPath .. "Time Dilation.ogg" },
	{ key = "Time Spiral", label = "EQOL: |cFF000000|rTime Spiral |T4622479:16|t", path = voiceoverPath .. "Time Spiral.ogg" },
	{ key = "Misdirection", label = "EQOL: |cFF000000|rMisdirection |T132180:16|t", path = voiceoverPath .. "Misdirection.ogg" },
	{ key = "Spellsteal", label = "EQOL: |cFF000000|rSpellsteal |T135729:16|t", path = voiceoverPath .. "Spellsteal.ogg" },
	{ key = "Chi-Ji", label = "EQOL: |cFF000000|rChi-Ji |T877514:16|t", path = voiceoverPath .. "Chi-Ji.ogg" },
	{ key = "Cocoon", label = "EQOL: |cFF000000|rCocoon |T627485:16|t", path = voiceoverPath .. "Cocoon.ogg" },
	{ key = "Revival", label = "EQOL: |cFF000000|rRevival |T1020466:16|t", path = voiceoverPath .. "Revival.ogg" },
	{ key = "Tiger's Lust", label = "EQOL: |cFF000000|rTiger's Lust |T651727:16|t", path = voiceoverPath .. "Tiger's Lust.ogg" },
	{ key = "Autumn", label = "EQOL: |cFF000000|rAutumn |T3636843:16|t", path = voiceoverPath .. "Autumn.ogg" },
	{ key = "Upgrade", label = "EQOL: Upgrade", path = voiceoverPath .. "Upgrade.ogg" },
	{ key = "Freedom", label = "EQOL: |cFF000000|rFreedom |T135968:16|t", path = voiceoverPath .. "Freedom.ogg" },
	{ key = "Devotion Aura", label = "EQOL: |cFF000000|rDevotion Aura |T135893:16|t", path = voiceoverPath .. "Devotion Aura.ogg" },
	{ key = "Lay on Hands", label = "EQOL: |cFF000000|rLay on Hands |T135928:16|t", path = voiceoverPath .. "Lay on Hands.ogg" },
	{ key = "Protection", label = "EQOL: |cFF000000|rProtection |T135964:16|t", path = voiceoverPath .. "Protection.ogg" },
	{ key = "Spellwarding", label = "EQOL: |cFF000000|rSpellwarding |T135880:16|t", path = voiceoverPath .. "Spellwarding.ogg" },
	{ key = "Sac", label = "EQOL: |cFF000000|rSac |T135966:16|t", path = voiceoverPath .. "Sac.ogg" },
	{ key = "Spring", label = "EQOL: |cFF000000|rSpring |T3636844:16|t", path = voiceoverPath .. "Spring.ogg" },
	{ key = "Summer", label = "EQOL: |cFF000000|rSummer |T3636845:16|t", path = voiceoverPath .. "Summer.ogg" },
	{ key = "Winter", label = "EQOL: |cFF000000|rWinter |T3636846:16|t", path = voiceoverPath .. "Winter.ogg" },
	{ key = "Barrier", label = "EQOL: |cFF000000|rBarrier |T253400:16|t", path = voiceoverPath .. "Barrier.ogg" },
	{ key = "Divine Hymn", label = "EQOL: |cFF000000|rDivine Hymn |T237540:16|t", path = voiceoverPath .. "Divine Hymn.ogg" },
	{ key = "Guardian Spirit", label = "EQOL: |cFF000000|rGuardian Spirit |T237542:16|t", path = voiceoverPath .. "Guardian Spirit.ogg" },
	{ key = "PI", label = "EQOL: |cFF000000|rPI |T135939:16|t", path = voiceoverPath .. "PI.ogg" },
	{ key = "Power Infusion", label = "EQOL: |cFF000000|rPower Infusion |T135939:16|t", path = voiceoverPath .. "Power Infusion.ogg" },
	{ key = "PS", label = "EQOL: |cFF000000|rPS |T135936:16|t", path = voiceoverPath .. "PS.ogg" },
	{ key = "Pain Suppression", label = "EQOL: |cFF000000|rPain Suppression |T135936:16|t", path = voiceoverPath .. "Pain Suppression.ogg" },
	{ key = "Shroud", label = "EQOL: |cFF000000|rShroud |T635350:16|t", path = voiceoverPath .. "Shroud.ogg" },
	{ key = "Tricks", label = "EQOL: |cFF000000|rTricks |T236283:16|t", path = voiceoverPath .. "Tricks.ogg" },
	{ key = "Ascendence", label = "EQOL: |cFF000000|rAscendence |T135791:16|t", path = voiceoverPath .. "Ascendence.ogg" },
	{ key = "Healing Tide", label = "EQOL: |cFF000000|rHealing Tide |T538569:16|t", path = voiceoverPath .. "Healing Tide.ogg" },
	{ key = "Spirit Link", label = "EQOL: |cFF000000|rSpirit Link |T237586:16|t", path = voiceoverPath .. "Spirit Link.ogg" },
	{ key = "SLT", label = "EQOL: |cFF000000|rSLT |T237586:16|t", path = voiceoverPath .. "SLT.ogg" },
	{ key = "Windrush", label = "EQOL: |cFF000000|rWindrush |T538576:16|t", path = voiceoverPath .. "Windrush.ogg" },
	{ key = "SS", label = "EQOL: |cFF000000|rSS |T136210:16|t", path = voiceoverPath .. "SS.ogg" },
	{ key = "Soulstone", label = "EQOL: |cFF000000|rSoulstone |T136210:16|t", path = voiceoverPath .. "Soulstone.ogg" },
	{ key = "Summonstone", label = "EQOL: |cFF000000|rSummonstone |T136223:16|t", path = voiceoverPath .. "Summonstone.ogg" },
	{ key = "Rallying Cry", label = "EQOL: |cFF000000|rRallying Cry |T132351:16|t", path = voiceoverPath .. "Rallying Cry.ogg" },
	{ key = "Stoneform", label = "EQOL: |cFF000000|rStoneform |T136225:16|t", path = voiceoverPath .. "Stoneform.ogg" },
	{ key = "Shadowmeld", label = "EQOL: |cFF000000|rShadowmeld |T132089:16|t", path = voiceoverPath .. "Shadowmeld.ogg" },
	{ key = "Water Walking", label = "EQOL: |cFF000000|rWater Walking |T135863:16|t", path = voiceoverPath .. "Water Walking.ogg" },
	{ key = "Trinket", label = "EQOL: Trinket", path = voiceoverPath .. "Trinket.ogg" },
	{ key = "Zephyr", label = "EQOL: |cFF000000|rZephyr |T4630449:16|t", path = voiceoverPath .. "Zephyr.ogg" },
	{ key = "Slow Fall", label = "EQOL: |cFF000000|rSlow Fall |T135992:16|t", path = voiceoverPath .. "Slow Fall.ogg" },
	{ key = "Aura Mastery", label = "EQOL: |cFF000000|rAura Mastery |T135872:16|t", path = voiceoverPath .. "Aura Mastery.ogg" },
	{ key = "Healthstones", label = "EQOL: |cFF000000|rHealthstones |T538745:16|t", path = voiceoverPath .. "Healthstones.ogg" },
	{ key = "Big Heal", label = "EQOL: Big Heal", path = voiceoverPath .. "Big Heal.ogg" },
	{ key = "Battle Res", label = "EQOL: Battle Res", path = voiceoverPath .. "Battle Res.ogg" },
	{ key = "Bloodlust", label = "EQOL: Bloodlust", path = voiceoverPath .. "Bloodlust.ogg" },
	{ key = "Cheat Death", label = "EQOL: Cheat Death", path = voiceoverPath .. "Cheat Death.ogg" },
	{ key = "Combat Res", label = "EQOL: Combat Res", path = voiceoverPath .. "Combat Res.ogg" },
	{ key = "Flask", label = "EQOL: Flask", path = voiceoverPath .. "Flask.ogg" },
	{ key = "Fly", label = "EQOL: Fly", path = voiceoverPath .. "Fly.ogg" },
	{ key = "Food", label = "EQOL: Food", path = voiceoverPath .. "Food.ogg" },
	{ key = "Sooth", label = "EQOL: |cFF000000|rSooth |T132163:16|t", path = voiceoverPath .. "Sooth.ogg" },
	{ key = "Wrath", label = "EQOL: |cFF000000|rWrath |T535045:16|t", path = voiceoverPath .. "Wrath.ogg" },
	{ key = "Purge", label = "EQOL: |cFF000000|rPurge |T136075:16|t", path = voiceoverPath .. "Purge.ogg" },
	{ key = "Weapon Enchant", label = "EQOL: Weapon Enchant", path = voiceoverPath .. "Weapon Enchant.ogg" },
	{ key = "Weapon Oil", label = "EQOL: Weapon Oil", path = voiceoverPath .. "Weapon Oil.ogg" },
	{ key = "Fireblood", label = "EQOL: |cFF000000|rFireblood |T1786406:16|t", path = voiceoverPath .. "Fireblood.ogg" },
	{ key = "Ancestral Call", label = "EQOL: |cFF000000|rAncestral Call |T2021574:16|t", path = voiceoverPath .. "Ancestral Call.ogg" },
	{ key = "Blood Fury", label = "EQOL: |cFF000000|rBlood Fury |T135726:16|t", path = voiceoverPath .. "Blood Fury.ogg" },
	{ key = "Berserking", label = "EQOL: |cFF000000|rBerserking |T135727:16|t", path = voiceoverPath .. "Berserking.ogg" },
	{ key = "Regeneratin", label = "EQOL: |cFF000000|rRegeneratin |T1850550:16|t", path = voiceoverPath .. "Regeneratin.ogg" },
	{ key = "Speed", label = "EQOL: Speed", path = voiceoverPath .. "Speed.ogg" },
	{ key = "Arcane Torrent", label = "EQOL: |cFF000000|rArcane Torrent |T136222:16|t", path = voiceoverPath .. "Arcane Torrent.ogg" },
	{ key = "Gift of the Naaru", label = "EQOL: |cFF000000|rGift of the Naaru |T135923:16|t", path = voiceoverPath .. "Gift of the Naaru.ogg" },
	{ key = "Tail Swipe", label = "EQOL: |cFF000000|rTail Swipe |T4622486:16|t", path = voiceoverPath .. "Tail Swipe.ogg" },
	{ key = "Wing Buffet", label = "EQOL: |cFF000000|rWing Buffet |T4622488:16|t", path = voiceoverPath .. "Wing Buffet.ogg" },
	{ key = "Escape Artist", label = "EQOL: |cFF000000|rEscape Artist |T132309:16|t", path = voiceoverPath .. "Escape Artist.ogg" },
	{ key = "Rocket Jump", label = "EQOL: |cFF000000|rRocket Jump |T370769:16|t", path = voiceoverPath .. "Rocket Jump.ogg" },
	{ key = "Bull Rush", label = "EQOL: |cFF000000|rBull Rush |T1723987:16|t", path = voiceoverPath .. "Bull Rush.ogg" },
	{ key = "Will to Survive", label = "EQOL: |cFF000000|rWill to Survive |T136129:16|t", path = voiceoverPath .. "Will to Survive.ogg" },
	{ key = "Haymaker", label = "EQOL: |cFF000000|rHaymaker |T2447782:16|t", path = voiceoverPath .. "Haymaker.ogg" },
	{ key = "Emergency Failsafe", label = "EQOL: |cFF000000|rEmergency Failsafe |T3192688:16|t", path = voiceoverPath .. "Emergency Failsafe.ogg" },
	{ key = "Quaking Palm", label = "EQOL: |cFF000000|rQuaking Palm |T572035:16|t", path = voiceoverPath .. "Quaking Palm.ogg" },
	{ key = "War Stomp", label = "EQOL: |cFF000000|rWar Stomp |T132368:16|t", path = voiceoverPath .. "War Stomp.ogg" },
	{ key = "Will of the Forsaken", label = "EQOL: |cFF000000|rWill of the Forsaken |T136187:16|t", path = voiceoverPath .. "Will of the Forsaken.ogg" },
	{ key = "Spatial Rift", label = "EQOL: |cFF000000|rSpatial Rift |T1724004:16|t", path = voiceoverPath .. "Spatial Rift.ogg" },
	{ key = "Darkflight", label = "EQOL: |cFF000000|rDarkflight |T366937:16|t", path = voiceoverPath .. "Darkflight.ogg" },
	{ key = "Enter Dungeon", label = "EQOL: Enter Dungeon", path = voiceoverPath .. "Enter Dungeon.ogg" },
	{ key = "Enter Follower Dungeon", label = "EQOL: Enter Follower Dungeon", path = voiceoverPath .. "Enter Follower Dungeon.ogg" },
	{ key = "Get Mage Food", label = "EQOL: Get Mage Food", path = voiceoverPath .. "Get Mage Food.ogg" },
	{ key = "Leave Dungeon", label = "EQOL: Leave Dungeon", path = voiceoverPath .. "Leave Dungeon.ogg" },
	{ key = "Check your Talents", label = "EQOL: Check your Talents", path = voiceoverPath .. "Check your Talents.ogg" },
	{ key = "Watch your Step", label = "EQOL: Watch your Step", path = voiceoverPath .. "Watch your Step.ogg" },
	{ key = "Wrong Talents", label = "EQOL: Wrong Talents", path = voiceoverPath .. "Wrong Talents.ogg" },
	{ key = "Buy Food", label = "EQOL: Buy Food", path = voiceoverPath .. "Buy Food.ogg" },
	{ key = "Consumables", label = "EQOL: Consumables", path = voiceoverPath .. "Consumables.ogg" },
	{ key = "Potion", label = "EQOL: Potion", path = voiceoverPath .. "Potion.ogg" },
	{ key = "Repair", label = "EQOL: Repair", path = voiceoverPath .. "Repair.ogg" },
	{ key = "Watch your Feet", label = "EQOL: Watch your Feet", path = voiceoverPath .. "Watch your Feet.ogg" },

	{ key = "Dispel", label = "EQOL: Dispel", path = voiceoverPath .. "Dispel.ogg" },
	{ key = "Silence", label = "EQOL: Silence", path = voiceoverPath .. "Silence.ogg" },
	{ key = "Soothe", label = "EQOL: Soothe", path = voiceoverPath .. "Soothe.ogg" },
	{ key = "Dispel Magic", label = "EQOL: Dispel Magic", path = voiceoverPath .. "Dispel Magic.ogg" },
	{ key = "Dispel Curse", label = "EQOL: Dispel Curse", path = voiceoverPath .. "Dispel Curse.ogg" },
	{ key = "Dispel Poison", label = "EQOL: Dispel Poison", path = voiceoverPath .. "Dispel Poison.ogg" },
	{ key = "Dispel Disease", label = "EQOL: Dispel Disease", path = voiceoverPath .. "Dispel Disease.ogg" },
	{ key = "Personal", label = "EQOL: Personal", path = voiceoverPath .. "Personal.ogg" },
	{ key = "Defensives", label = "EQOL: Defensives", path = voiceoverPath .. "Defensives.ogg" },
	{ key = "Externals", label = "EQOL: Externals", path = voiceoverPath .. "Externals.ogg" },
	{ key = "Use cooldowns", label = "EQOL: Use cooldowns", path = voiceoverPath .. "Use cooldowns.ogg" },
	{ key = "Hold cooldowns", label = "EQOL: Hold cooldowns", path = voiceoverPath .. "Hold cooldowns.ogg" },
	{ key = "Stop DPS", label = "EQOL: Stop DPS", path = voiceoverPath .. "Stop DPS.ogg" },
	{ key = "Hard stop", label = "EQOL: Hard stop", path = voiceoverPath .. "Hard stop.ogg" },
	{ key = "Wipe", label = "EQOL: Wipe", path = voiceoverPath .. "Wipe.ogg" },
	{ key = "Reset", label = "EQOL: Reset", path = voiceoverPath .. "Reset.ogg" },
	{ key = "Execute", label = "EQOL: Execute", path = voiceoverPath .. "Execute.ogg" },
	{ key = "Priority target", label = "EQOL: Priority Target", path = voiceoverPath .. "Priority Target.ogg" },
	{ key = "Front", label = "EQOL: Front", path = voiceoverPath .. "Front.ogg" },
	{ key = "Forward", label = "EQOL: Forward", path = voiceoverPath .. "Forward.ogg" },
	{ key = "Behind", label = "EQOL: Behind", path = voiceoverPath .. "Behind.ogg" },
	{ key = "Center", label = "EQOL: Center", path = voiceoverPath .. "Center.ogg" },
	{ key = "Middle", label = "EQOL: Middle", path = voiceoverPath .. "Middle.ogg" },
	{ key = "Edge", label = "EQOL: Edge", path = voiceoverPath .. "Edge.ogg" },
	{ key = "Corner", label = "EQOL: Corner", path = voiceoverPath .. "Corner.ogg" },
	{ key = "North", label = "EQOL: North", path = voiceoverPath .. "North.ogg" },
	{ key = "South", label = "EQOL: South", path = voiceoverPath .. "South.ogg" },
	{ key = "East", label = "EQOL: East", path = voiceoverPath .. "East.ogg" },
	{ key = "West", label = "EQOL: West", path = voiceoverPath .. "West.ogg" },
	{ key = "Northeast", label = "EQOL: Northeast", path = voiceoverPath .. "Northeast.ogg" },
	{ key = "Northwest", label = "EQOL: Northwest", path = voiceoverPath .. "Northwest.ogg" },
	{ key = "Southeast", label = "EQOL: Southeast", path = voiceoverPath .. "Southeast.ogg" },
	{ key = "Southwest", label = "EQOL: Southwest", path = voiceoverPath .. "Southwest.ogg" },
	{ key = "Upstairs", label = "EQOL: Upstairs", path = voiceoverPath .. "Upstairs.ogg" },
	{ key = "Downstairs", label = "EQOL: Downstairs", path = voiceoverPath .. "Downstairs.ogg" },
	{ key = "Portal", label = "EQOL: Portal", path = voiceoverPath .. "Portal.ogg" },
	{ key = "Sidestep", label = "EQOL: Sidestep", path = voiceoverPath .. "Sidestep.ogg" },
	{ key = "Safe", label = "EQOL: Safe", path = voiceoverPath .. "Safe.ogg" },
	{ key = "Unsafe", label = "EQOL: Unsafe", path = voiceoverPath .. "Unsafe.ogg" },
	{ key = "Safe zone", label = "EQOL: Safe zone", path = voiceoverPath .. "Safe zone.ogg" },
	{ key = "Cone", label = "EQOL: Cone", path = voiceoverPath .. "Cone.ogg" },
	{ key = "Meteor", label = "EQOL: Meteor", path = voiceoverPath .. "Meteor.ogg" },
	{ key = "Orbs", label = "EQOL: Orbs", path = voiceoverPath .. "Orbs.ogg" },
	{ key = "Tornadoes", label = "EQOL: Tornadoes", path = voiceoverPath .. "Tornadoes.ogg" },
	{ key = "Swirlies", label = "EQOL: Swirlies", path = voiceoverPath .. "Swirlies.ogg" },
	{ key = "Donut", label = "EQOL: Donut", path = voiceoverPath .. "Donut.ogg" },
	{ key = "Pizza slice", label = "EQOL: Pizza slice", path = voiceoverPath .. "Pizza slice.ogg" },
	{ key = "Puddles", label = "EQOL: Puddles", path = voiceoverPath .. "Puddles.ogg" },
	{ key = "Lines", label = "EQOL: Lines", path = voiceoverPath .. "Lines.ogg" },
	{ key = "Healers", label = "EQOL: Healers", path = voiceoverPath .. "Healers.ogg" },
	{ key = "Tanks", label = "EQOL: Tanks", path = voiceoverPath .. "Tanks.ogg" },
	{ key = "DPS", label = "EQOL: DPS", path = voiceoverPath .. "DPS.ogg" },
	{ key = "Taunt swap", label = "EQOL: Taunt swap", path = voiceoverPath .. "Taunt swap.ogg" },
	{ key = "Pull in five", label = "EQOL: Pull in five", path = voiceoverPath .. "Pull in five.ogg" },
	{ key = "Pull in ten", label = "EQOL: Pull in ten", path = voiceoverPath .. "Pull in ten.ogg" },
	{ key = "Phase", label = "EQOL: Phase", path = voiceoverPath .. "Phase.ogg" },
	{ key = "Phase two", label = "EQOL: Phase two", path = voiceoverPath .. "Phase two.ogg" },
	{ key = "Healthstone", label = "EQOL: Healthstone", path = voiceoverPath .. "Healthstone.ogg" },
	{ key = "Health Potion", label = "EQOL: Health Potion", path = voiceoverPath .. "Health Potion.ogg" },
	{ key = "Mana Potion", label = "EQOL: Mana Potion", path = voiceoverPath .. "Mana Potion.ogg" },
	{ key = "Drink", label = "EQOL: Drink", path = voiceoverPath .. "Drink.ogg" },
	{ key = "OOM", label = "EQOL: OOM", path = voiceoverPath .. "OOM.ogg" },
	{ key = "Offhealing active", label = "EQOL: Offhealing active", path = voiceoverPath .. "Offhealing active.ogg" },
	{ key = "Beacon", label = "EQOL: |cFF000000|rBeacon |T236247:16|t", path = voiceoverPath .. "Beacon.ogg" },

	-- Crafting order
	{ key = "New Crafting Order", label = "EQOL: Crafting Order - New", path = voiceoverPath .. "New Crafting Order.ogg" },
	{ key = "Canceled Crafting Order", label = "EQOL: Crafting Order - Canceled", path = voiceoverPath .. "Canceled Crafting Order.ogg" },
}

-- Sort alphabetically, but ignore the leading "EQOL:" prefix (and any following spaces)
local function labelKey(lbl) return (lbl:gsub("^EQOL:%s*", "")):lower() end

table.sort(addon.SharedMedia.sounds, function(a, b) return labelKey(a.label) < labelKey(b.label) end)
